import { logger } from "@/lib/logger";

interface AIOptions {
    apiKey?: string | null;
    provider?: string | null;
}

const DEFAULT_SYSTEM_INSTRUCTION = `You are a smart, concise WhatsApp AI Assistant. 
Guidelines:
- Answer accurately and directly.
- Use WhatsApp markdown formatting: *bold* for key terms, _italic_ for emphasis, \`code\` for code, and neat bullet points.
- Keep answers readable on a phone screen (concise paragraphs, not endless walls of text).`;

/**
 * Sends a query to the configured AI provider (Gemini or OpenAI).
 */
export async function askAI(prompt: string, options?: AIOptions): Promise<string> {
    const provider = (options?.provider || "gemini").toLowerCase();
    const apiKey = options?.apiKey?.trim() || 
        (provider === "openai" ? process.env.OPENAI_API_KEY : process.env.GEMINI_API_KEY);

    if (!apiKey) {
        return (
            "⚠️ *AI API Key not configured!*\n\n" +
            "To use this feature, please get a free Gemini API key at:\n" +
            "👉 https://aistudio.google.com/app/apikey\n\n" +
            "Then paste it in *Dashboard ➡️ Bot Settings ➡️ AI Assistant*."
        );
    }

    try {
        if (provider === "openai") {
            return await askOpenAI(prompt, apiKey);
        } else {
            return await askGemini(prompt, apiKey);
        }
    } catch (err: any) {
        logger.error("AIService", "Error calling AI:", err);
        return `❌ *AI Error:* ${err.message || "Failed to generate answer. Please check your API key."}`;
    }
}

/**
 * Google Gemini REST API call (no external SDK required)
 */
async function askGemini(prompt: string, apiKey: string): Promise<string> {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;

    const res = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
            system_instruction: {
                parts: [{ text: DEFAULT_SYSTEM_INSTRUCTION }]
            },
            contents: [
                {
                    role: "user",
                    parts: [{ text: prompt }]
                }
            ],
            generationConfig: {
                temperature: 0.7,
                maxOutputTokens: 1000
            }
        })
    });

    if (!res.ok) {
        const errorData = await res.json().catch(() => ({}));
        const msg = errorData?.error?.message || `HTTP ${res.status} ${res.statusText}`;
        throw new Error(msg);
    }

    const data = await res.json();
    const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!text) {
        throw new Error("No response generated by Gemini.");
    }

    return text.trim();
}

/**
 * OpenAI REST API call
 */
async function askOpenAI(prompt: string, apiKey: string): Promise<string> {
    const url = "https://api.openai.com/v1/chat/completions";

    const res = await fetch(url, {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify({
            model: "gpt-4o-mini",
            messages: [
                { role: "system", content: DEFAULT_SYSTEM_INSTRUCTION },
                { role: "user", content: prompt }
            ],
            temperature: 0.7,
            max_tokens: 1000
        })
    });

    if (!res.ok) {
        const errorData = await res.json().catch(() => ({}));
        const msg = errorData?.error?.message || `HTTP ${res.status} ${res.statusText}`;
        throw new Error(msg);
    }

    const data = await res.json();
    const text = data?.choices?.[0]?.message?.content;
    if (!text) {
        throw new Error("No response generated by OpenAI.");
    }

    return text.trim();
}

/**
 * Cleans raw HTML to extract readable text content.
 */
function extractArticleText(html: string): { title: string; text: string } {
    // Extract title
    let title = "";
    const ogTitleMatch = html.match(/<meta[^>]*property=["']og:title["'][^>]*content=["']([^"']+)["']/i);
    const titleMatch = html.match(/<title[^>]*>([^<]+)<\/title>/i);
    if (ogTitleMatch && ogTitleMatch[1]) {
        title = ogTitleMatch[1].trim();
    } else if (titleMatch && titleMatch[1]) {
        title = titleMatch[1].trim();
    }

    // Remove script, style, nav, footer, noscript tags
    let cleaned = html
        .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, "")
        .replace(/<style\b[^<]*(?:(?!<\/style>)<[^<]*)*<\/style>/gi, "")
        .replace(/<nav\b[^<]*(?:(?!<\/nav>)<[^<]*)*<\/nav>/gi, "")
        .replace(/<footer\b[^<]*(?:(?!<\/footer>)<[^<]*)*<\/footer>/gi, "")
        .replace(/<header\b[^<]*(?:(?!<\/header>)<[^<]*)*<\/header>/gi, "")
        .replace(/<noscript\b[^<]*(?:(?!<\/noscript>)<[^<]*)*<\/noscript>/gi, "");

    // Strip HTML tags
    cleaned = cleaned.replace(/<[^>]+>/g, " ");

    // Decode basic HTML entities
    cleaned = cleaned
        .replace(/&amp;/g, "&")
        .replace(/&lt;/g, "<")
        .replace(/&gt;/g, ">")
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/&nbsp;/g, " ");

    // Normalize whitespaces
    cleaned = cleaned.replace(/\s+/g, " ").trim();

    return { title: title || "Web Article", text: cleaned };
}

/**
 * Fetches an article by URL and generates a structured summary.
 */
export async function summarizeUrl(url: string, options?: AIOptions): Promise<string> {
    try {
        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), 12000); // 12 second fetch timeout

        const response = await fetch(url, {
            signal: controller.signal,
            headers: {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
            }
        });

        clearTimeout(timeout);

        if (!response.ok) {
            return `❌ Could not open link (HTTP ${response.status}). The page might be private or blocked.`;
        }

        const html = await response.text();
        const { title, text } = extractArticleText(html);

        if (!text || text.length < 120) {
            return "❌ Could not extract enough readable text from this page (it might require Javascript or login).";
        }

        // Limit content to ~6000 characters to fit token budget
        const contentSnippet = text.slice(0, 6000);

        const prompt = 
            `Please provide an insightful, highly readable summary of the following article for WhatsApp.\n\n` +
            `Formatting requirements:\n` +
            `1. Start with a 1-line bold overview.\n` +
            `2. List 3 to 5 clear, bulleted key points (using •).\n` +
            `3. End with a 1-line "💡 Takeaway:" summary.\n\n` +
            `Article Title: ${title}\n` +
            `Article Content:\n${contentSnippet}`;

        const summary = await askAI(prompt, options);

        return `📰 *Summary: ${title}*\n🔗 _${url}_\n\n${summary}\n\n⏱️ _Read in ~20 seconds_`;

    } catch (err: any) {
        logger.error("AIService", "Error summarizing URL:", err);
        if (err.name === "AbortError") {
            return "❌ Request timed out while loading the link. Please try again.";
        }
        return `❌ Failed to summarize link: ${err.message || "Unknown error"}`;
    }
}
